"""add public footer comments

Revision ID: 532c38f0e9ad
Revises: 48d14a753602
Create Date: 2026-01-08 10:35:20.570481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532c38f0e9ad'
down_revision = '48d14a753602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_comment')
    # ### end Alembic commands ###
