"""koma_max column add in comic table

Revision ID: 6fabf4f88108
Revises: 
Create Date: 2025-12-19 11:02:28.892207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fabf4f88108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_koma', sa.Integer(), nullable=True))
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('koma', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('koma', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('max_koma')

    # ### end Alembic commands ###
